version: '3.9'

services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bikedb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: